# Generated by Django 2.2.7 on 2019-11-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_offer',
            field=models.BooleanField(default=False),
        ),
    ]
