# Generated by Django 2.2.7 on 2019-11-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_orderitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
