# Generated by Django 2.2.7 on 2019-11-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_remove_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
